version: '3.9'

services:
  simple-wms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-wms
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
