"""empty message

Revision ID: 003f3f7c99c1
Revises: d888ef179d8e
Create Date: 2025-06-04 11:42:24.520175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003f3f7c99c1'
down_revision: Union[str, None] = 'd888ef179d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('urgent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missions', 'urgent')
    # ### end Alembic commands ###
