"""Adding urgent column to mission table

Revision ID: 3147bd49fdc4
Revises: e6c007a09a72
Create Date: 2025-06-06 13:51:50.854694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3147bd49fdc4'
down_revision: Union[str, None] = 'e6c007a09a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('urgent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missions', 'urgent')
    # ### end Alembic commands ###
