"""Initial schema

Revision ID: 383cb670f182
Revises: 0c42e35c46f9
Create Date: 2025-06-04 12:02:45.676661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '383cb670f182'
down_revision: Union[str, None] = '0c42e35c46f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('implantations', sa.Column('commentaires', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('implantations', 'commentaires')
    # ### end Alembic commands ###
