"""Initial schema

Revision ID: e9a0db93e57e
Revises: 58bea15ce99e
Create Date: 2025-06-04 11:41:47.961597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a0db93e57e'
down_revision: Union[str, None] = '58bea15ce99e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('urgent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missions', 'urgent')
    # ### end Alembic commands ###
