"""Initial schema

Revision ID: f87931e6addc
Revises: 003f3f7c99c1
Create Date: 2025-06-06 14:56:51.535628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f87931e6addc'
down_revision: Union[str, None] = '003f3f7c99c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missions', 'urgent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('urgent', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
