"""Initial schema

Revision ID: fb342152f8f6
Revises: e6c007a09a72
Create Date: 2025-06-22 14:57:24.711950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb342152f8f6'
down_revision: Union[str, None] = 'e6c007a09a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.create_foreign_key(None, 'reservation', 'salle', ['salle_id'], ['id'])
    op.add_column('salle', sa.Column('disponible', sa.Boolean(), nullable=False))
    op.alter_column('salle', 'localisation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('salle', 'localisation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('salle', 'disponible')
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.create_foreign_key(None, 'reservation', 'salle', ['salle_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
