name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure Poetry to not create virtualenvs (use system env)
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
          poetry add --dev flake8 black pytest coverage

      - name: Run linter (flake8)
        run: |
          poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      - name: Check formatting (black)
        run: |
          poetry run black --check .

      - name: Run tests and generate coverage report
        run: |
          poetry run coverage run -m pytest
          poetry run coverage report
          poetry run coverage xml
          poetry run coverage html

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage.xml
            htmlcov/
